const gw = [
    "bakt potet",
    "kinesisk mur",
    "cannada",
    "sylvi listhaug",
    "jack sparrow",
    "sherlock holmes",
    "jodle kid",
    "beer to the face smash chug girl",
    "frihet",
    "erna solberg",
    "en god kopp kaffe",
    "elvis presley",
    "norge",
    "pc",
    "bok",
    "et majestetisk tre",
    "en fin delfin",
    "en kul ku",
    "et bankran",
    "coechella",
    "drita rita",
    "en vakker sommerkveld",
];

module.exports = gw;
